version: "3.9"
services:
  pet_store_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  pet_store_app:
    image: pet_store_service
    ports:
      - "1000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose
    depends_on:
      - pet_store_db
